language: python
cache: pip

matrix:
  include:
    - env: TOXENV=py27-dj18
      python: 2.7
    - env: TOXENV=py27-dj110
      python: 2.7
    - env: TOXENV=py35-dj18
      python: 3.5
    - env: TOXENV=py35-dj110
      python: 3.5

install:
  pip install tox coveralls

script:
  tox

after_success:
  coveralls
